name: woocommerce_nylo_slate
description: A Slate package to quickly start your next woocommerce flutter project.
version: 0.0.1
repository: https://github.com/loaidev64/woocommerce_rest_api_toolkit.git
homepage: https://github.com/loaidev64/woocommerce_rest_api_toolkit.git
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  nylo_support: ^5.57.0
  flutter:
    sdk: flutter
  args: ^2.4.2
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# screenshots:
#   - description: The package logo.
#     path: screenshots/logo.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
